FROM ghcr.io/parkervcp/installers:debian

ENV AUTO_UPDATE=1
ENV GAME_MODE=normal
ENV SRV_PW=changeme
ENV SRCDS_APPID=2465200
ENV SRV_NAME="Pterodactyl hosted Server"
ENV WINDOWS_INSTALL=1
ENV WINEDEBUG=-all
ENV WINETRICKS_RUN="mono vcrun2019"
ENV BLOBSYNC_PORT=9700
ENV MAX_PLAYERS=4
ENV QUERY_PORT=27016
ENV SAVE_SLOT=0000000001
ENV SKIP_TESTS=false
ENV WINEARCH=win64
ENV WINEPATH=/home/container

COPY rootfs /

ENTRYPOINT ["/entrypoint.sh"]
